# Generated by Django 5.2.7 on 2025-10-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=15)),
                ("parent_phone", models.CharField(max_length=15)),
                ("register_no", models.CharField(max_length=15, unique=True)),
                ("branch", models.CharField(max_length=100)),
                ("age", models.PositiveIntegerField()),
                ("password", models.CharField(max_length=100)),
            ],
        ),
    ]
